cask_args appdir: '/Applications'

# Taps
tap 'homebrew/bundle'
tap 'azure/draft'
tap 'weaveworks/tap'

brew 'warrensbox/tap/tfswitch'
brew 'ack' # grep
brew 'ansible'
brew 'bat' # cat
brew 'coreutils'
brew 'fd' # find
brew 'fzf' # fuzzy finder
brew 'gpg2'
brew 'hub'
brew 'fx' # Command-line JSON processing tool
brew 'imagemagick'
brew 'jq' # json query
brew 'openssl'
brew 'readline'
brew 'switchaudio-osx'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions' 
brew 'zsh-git-prompt' 
brew 'zsh-history-substring-search'
brew 'zsh-navigation-tools'
brew 'powerlevel9k'
brew 'ranger'
brew 'ack'
brew 'grc'
brew 'htop'
brew 'ctop'
brew 'nmap'
brew 'unrar'
brew 'wget'
brew 'curl' #, args: ['with-openssl']
brew 'git'
brew 'git-flow'
brew 'awscli'
brew 'aws-iam-authenticator'
brew 's3cmd'
brew 'kubectl'
brew 'azure-cli'
brew 'eksctl'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'helmfile'
brew 'fluxctl'
brew 'chamber'
brew 'kops'
brew 'kubectx'
brew 'terragrunt'
brew 'nomad'
brew 'vault'
brew 'consul'
brew 'packer'
brew 'ansible'
brew 'skaffold'
brew 'tmux'
brew 'coreutils'
brew 'kube-ps1'
brew 'draft'
brew 'fzf'


cask 'visual-studio-code'
cask 'firefox'
cask 'iterm2'
cask 'github'
cask 'appzapper'
cask 'sysdig-inspect'
cask 'aws-vault'
cask 'drawio'
